### PR TITLE
Update Sequence class

### PR DESCRIPTION
**Pull request by weikang9009**
This PR is to:
* clean and update [Sequence class](https://github.com/spatialucr/osnap/blob/master/osnap/analyze/dynamics.py#L88):
    * clean the docstrings
    * optimize the calculation of sequence distance matrix - speed up
    * add the transition-oriented OM
* add a reference webpage to docs

### CODE REVIEW

**Comment by weikang9009** [comment]
`indel` is more standard in the literature. `Cost` should be comprised of substitution and indel costs.

**Comment by knaaptime** [comment]
there's a standard for a function parameter name in the literature? Point taken on the fact that cost is ambiguous because it could also refer to substitution, but at first glance it's not obvious to me that `indel` refers to insertion or deletion, so I'm just trying to make sure the signature is as intuitive as possible

**Comment by knaaptime** [comment]
you're definitely right, `indel` is used all the time in the literature, so lets just keep it, but I imagine many people trying out OSNAP for the first time could be unfamiliar with the sequence analysis/optimal matching literature so my concern was making sure its obvious what that refers to

**Comment by weikang9009** [comment]
I see. [The docstring for this variable](https://github.com/weikang9009/osnap/blob/seq/osnap/analyze/dynamics.py#L111) clarifies that it refers to insertion/deletion cost.

**Comment by knaaptime** [comment]
+1

**Comment by weikang9009** [comment]
I've added one sequence analysis paper to references and cited in the doctrings of `Sequence`. We can definitely add more.

**Pull request merged**
