### PR TITLE
[WIP] Make san diego & DC datasets 

### PR DESCRIPTION
**Pull request by ljwolf**
This was a bit more complicated than expected. 

1. I had to update variable mapping for 2000 census, since the ACS variable codes that are already in `variables.csv` are not the same as the variables in the decennial census stuff. 
2. the 2000 SF3 is only available at block-group, so that'd be the lowest common geometry. I've pulled down tract for now. 
3. If we make the cells valid arithmetic, we can use `DataFrame.eval()` to get all computed columns. But, this means we need to parse the formula, get all its symbols, and grab those from the API. Patsy probably can do this, but I did it manually, in a way allowing for column ranges using R-style colons to stand in for ranges. So, like, `PCT012J068:105 + PCT012J172:209` is the sum of all columns between `PCT012J068` and `PCT012J105` plus the sum of columns between `PCT012J172` and `PCT012J209`. 
4. The change from `convert_objects()` to `infer_objects()` in pandas makes cenpy a lot less cool, since the `dtypes` in nearly all sparsely-populated columns are now string-type. `covert_objects()` used to pretty much force anything that could be numericized into numbers. I may write a new `maybe_cast_to_float` and use that everywhere, since we nearly always want stuff numerical if it is not a string. 

What is left:

0. concatenate san_diego_sf1_processed/san_diego_sf3_processed along axis=1
1. pull the applicable ltdb names from `variables` and make them the column names of the right elements of `san_diego_sf*`
2. Concatenate the `*_processed` dataframes alongside the metadata columns, obtained from `[col for col in san_diego_sf1.columns if col not in sf1cols]`
3. merge this new concatenated data together between sf1 and sf3.

### CODE REVIEW

**Comment by knaaptime** [comment]
wow i had no idea you could use ranges and stuff in `.eval`

**Comment by knaaptime** [comment]
i need to stick an assignment inside the `.eval`... something like

`_sf3[sf3cols].astype(float).eval(variables['variable'] + "=" +normalize_relation(rel))`

though i doubt you can concat inside the eval call

**Comment by ljwolf** [comment]
hmm... I see what you mean, but I'm not sure that's possible. `assign` is how I think that's supposed to go. What's the reason for the assign statement?

**Comment by ljwolf** [comment]
I think any `(n,)` or `(n,1)` shaped datastructure will get correctly assigned to a column. 

```python
df = pd.DataFrame({'a':[1,2,3], 'b':[2,3,4]})
df['c'] = df[['a']] # double brackets extracts as a df
```

**Comment by ljwolf** [comment]
If there's more than one column though... good q.

**Comment by knaaptime** [comment]
ok,excellent.

i'm trying to make sure i understand what cenpy is going to give back so I can do the renaming. I wasnt sure if the columns would look like `P012J018+P012J019+...+P012J108` after they're processed

It occurs to me that instead of doing a dictionary rename like i'd planned, it might be simpler to just use list instead... after concatenating the processed dfs together, we should know the length and order of the columns and could just set `df.columns = variables['variables'].dropna().tolist()`?

**Pull request merged**
